version: '3'

services:
  app:
    image: app
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3333:3333
    depends_on:
      - db
  db:
    image: mysql
    container_name: db
    restart: always
    environment:
      MYSQL_DATABASE: botApp
      MYSQL_ROOT_PASSWORD: IXMbFCzlUp4F7JWi
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - 3306:3306